---
- name: Setup K3s on Server Node
  hosts: server
  become: yes
  tasks:
    - name: Install K3s on Server Node
      shell: |
        curl -sfL https://get.k3s.io | K3S_VERSION={{ k3s_version }} sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Get the K3s token to share with agent nodes
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Copy Kubeconfig file to local machine (optional)
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./kubeconfig
        flat: yes

    - name: Restart K3s service on Server Node
      systemd:
        name: k3s
        state: restarted

- name: Setup K3s on Agent Nodes
  hosts: agent
  become: yes
  tasks:
    - name: Install K3s on Agent Node
      shell: |
        curl -sfL https://get.k3s.io | K3S_VERSION={{ k3s_version }} K3S_URL=https://{{ hostvars[groups['server'][0]].ansible_default_ipv4.address }}:6443 K3S_TOKEN={{ hostvars[groups['server'][0]].k3s_token.stdout }} sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Restart K3s agent service on Agent Node
      systemd:
        name: k3s-agent
        state: restarted
